global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Threading;
global using mupdf;
global using MuPDF.NET;
global using PDF4LLM;
global using static global::PDF4LLM.Pdf4LLM;
global using PDF4LLM.Helpers;
global using PDF4LLM.Llama;
global using PDF4LLM.Ocr;
global using SkiaSharp;
global using Box = MuPDF.NET.Box;
global using Encoding = System.Text.Encoding;
global using File = System.IO.File;
global using Font = MuPDF.NET.Font;
global using Morph = MuPDF.NET.Morph;
global using TextWriter = MuPDF.NET.TextWriter;
global using Utils = MuPDF.NET.Utils;
